### ISSUE TITLE
Question: customizing icon

### ISSUE THREAD

**Issue by unindented** [paulcbetts/grunt-build-atom-shell#10]
What would be the best way to automate the customization of the app icon with your grunt task?

**Comment by paulcbetts** [comment]
@unindented In Atom and Atom Shell Starter, the EXE icon is set post-build: https://github.com/atom/atom-shell-starter/blob/master/build/tasks/set-exe-icon-task.coffee - you *could* rig the icon pre-build, but there isn't much advantage in doing so, since you have to effectively fork the repo just for that change

**Comment by unindented** [comment]
Good to know. Thank you!
